Transcendence/Api/urls.py
from django.urls import path
import Api.Profile.views as profile_views
import Api.Chat.views as chat_views
import Api.TwoFa.views as TwoFa_views
import Api.FtAuth.views as ft_views
import Api.views as views
import Api.Match.views as match_views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView, TokenBlacklistView
import Api.Pong.views as pong_views
import Api.Gdpr.views as gdpr_views

urlpatterns = [
    # profil
    path('profile/', profile_views.product_alt_view),
    path('profile/<username>/', profile_views.product_alt_view),
    path('profile/<username>/edit/', profile_views.product_alt_view),

    # Chat
    path('block/', chat_views.UserBlockAPIView.as_view(), name='block'),

    # Two Fa
    path('two-fa/', TwoFa_views.two_fa.as_view(), name='two_fa'),
    path('enable-2fa/', TwoFa_views.enable_2fa.as_view(), name='enable_2fa'),
    path('disable-2fa/', TwoFa_views.disable_2fa.as_view(), name='disable_2fa'),
    path('verify-2fa/', TwoFa_views.verify_2fa.as_view(), name='verify_2fa'),

    # 42 Auth
    path('login_with_42/', ft_views.LoginWithFourtyTwoAuth.as_view(), name='login_with_42'),
    path('redirect_auth/', ft_views.CallbackView.as_view(), name='callback'),
    
    # General Login Register
    path('check/login/', views.CheckLoginStatus.as_view(), name='check_login_status'),
    path('login/', views.UserLoginAPIView.as_view(), name="api-login"),
    path('register/', views.UserRegisterAPIView.as_view(), name="api-register"),

    # Match
    path('match/', match_views.MatchPostAPIView.as_view(), name="match"),
    path('matchget/<str:username>/', match_views.MatchGetAPIView.as_view(), name="matchget"),

    # Pong
    path('ponginvite/', pong_views.PongInviteCreateAPIView.as_view(), name="ponginvitepost"),
    path('ponginviteget/<str:inv_id>', pong_views.PongInviteGetAPIView.as_view(), name="ponginviteget"),
    path('ponginviteput/<str:inv_id>', pong_views.PongInviteUpdateAPIView.as_view(), name="ponginviteput"),
    path('ponginvitedel/<str:inv_id>', pong_views.PongInviteDeleteAPIView.as_view() , name="ponginvitedel"),

    # Token
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('token/blacklist/', TokenBlacklistView.as_view(), name='blacklist_token'),

    # GDPR
    path('delete/<str:username>/', gdpr_views.DeleteObjectView.as_view(), name='gdpr_delete'),

]

Transcendence/Display/urls.py
# urls.py in Django
from django.urls import path
from Display.views import *
from Chat import views as Chat_views
from Pong import views as Pong_views

urlpatterns = [

    path('logout', logoutUser, name="logout"),

#	HOME PAGE
	path('', basePage, name='basePage'),
    path('login/', basePage, name='basePage'),
#	HOME ENDPOINTS
	path('get-file/home/<str:filename>', homePage, name='homePage'),

#	PROFILE PAGE
	path('profile', basePage, name='basePage'),
    path('profile/<str:username>', customSomething, name='customSomething'),
    path('get-file/username', customProfile, name='customProfile'),
#	PROFILE ENDPOINTS
	path('get-file/profile/<str:filename>', profilePage, name='homePage'),


#   ---------------------------------------------------------------------------------------------------------------------------
#	SETTINGS PAGE
	path('settings', basePage, name='basePage'),
#	SETTINGS ENDPOINTS
	path('get-file/settings/<str:filename>', settingsPage, name='settingsPage'),

#   ---------------------------------------------------------------------------------------------------------------------------
#   LOGIN PAGE
    path('login', basePage, name='login'),
#   LOGIN ENDPOINTS
    path('get-file/login/<str:filename>', loginPage, name='loginPage'),

#   REGISTER PAGE
    path('register', basePage, name='register'),
#   REGISTER ENDPOINTS
    path('get-file/register/<str:filename>', registerPage, name='registerPage'),


#   CHAT PAGE
	path('chat', basePage, name='basePage'),
#   CHAT ENDPOINTS
    path('get-file/chat/<str:filename>', Chat_views.chatPage, name='chatPage'),

#   About Page
    path('about', basePage, name='basePage'),
#   About ENDPOINTS
    path('get-file/about/<str:filename>', aboutPage, name='aboutPage'),

#	Game Page
	path('pong', basePage, name='basePage'),
	path('get-file/pong/<str:filename>', Pong_views.pongPage, name='pongPage'),

# Add other URL patterns or catch-all patterns

#   tournament Page
    path('tournament', basePage, name='basePage'),
#   tournament ENDPOINTS
    path('get-file/tournament/<str:filename>', tournamentPage, name='tournamentPage'),

#   Vs Page
    path('vs', basePage, name='basePage'),
#   vs ENDPOINTS
    path('get-file/vs/<str:filename>', vsPage, name='vsPage'),

#   42 Auth redirection.
    path('ft_login/', basePage, name='basePage'),
]

Transcendence/Pong/urls.py
# urls.py in Django
from django.urls import path
from Pong.views import *
from Display.views import basePage
from Api import views as Api_views
from Chat import views as Chat_views

urlpatterns = [
#   GAME PAGE
]

Transcendence/Transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Display.urls')),
    path('chat/', include('Chat.urls')),
    path('api/', include('Api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Transcendence/Api/Pong/models.py
from django.db import models

class PongInvite(models.Model):
    invite_id = models.CharField(max_length=100)
    invitee = models.CharField(max_length=100)
    invited = models.CharField(max_length=100)
    is_active = models.IntegerField(default=0)

    def __str__(self):
        return self.invite_id

Transcendence/Chat/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from rest_framework_simplejwt.tokens import RefreshToken
# Create your models here.

class CustomUser(AbstractUser):
    friends = models.ManyToManyField("self", blank=True, symmetrical=False, related_name='friend')
    blockeds = models.ManyToManyField("BlockedUser", blank=True, symmetrical=False, related_name='blockeds')
    is_2fa_enabled = models.BooleanField(default=False)
    jwt_secret = models.CharField(max_length=100, default='')
    
    total_match = models.IntegerField(default=0)
    win = models.IntegerField(default=0)
    lose = models.IntegerField(default=0)
    bio = models.TextField(default='Bio not set yet.')
    online_status = models.BooleanField(default=False)
    is_42_student = models.BooleanField(default=False)

    LANGUAGES = {
        ('EN', 'English'),
        ('TR', 'Turkish'),
        ('FR', 'French'),
    }

    language = models.CharField(max_length=2, choices=LANGUAGES, default='EN')

    #profile photo
    def where_to_upload(self,filename):
        return f'profile_pictures/{self.username}/{filename}'

    profile_picture = models.ImageField(upload_to=where_to_upload, default="default/default.jpg")

    def get_friends_name(self):
        return self.friends.all().values_list(flat=True)
    
    def get_token(self):
        refresh = RefreshToken.for_user(self)
        return ({
            'refresh': str(refresh),
            'access': str(refresh.access_token)
        })

    def __str__(self):
        return self.username
    

    class Meta:
        ordering = ('username',)


class Room(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)


class Message(models.Model):
    user = models.ForeignKey(CustomUser, related_name='whoSend', on_delete=models.CASCADE, null=True)
    friend = models.ForeignKey(CustomUser, related_name='whoRecv', on_delete=models.CASCADE, null=True)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def getDate(self):
        return self.date_added.date().__str__()

    class Meta:
        ordering = ('date_added',)


class BlockedUser(models.Model):
    user = models.ForeignKey(CustomUser, related_name='whoBlock', on_delete=models.CASCADE, null=True)
    blocked = models.ForeignKey(CustomUser, related_name='whoBlocked', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.blocked.username)
    
    class Meta:
        ordering = ('blocked',)

class FriendRequest(models.Model):
    sender = models.ForeignKey(CustomUser, related_name='whoSendRequest', on_delete=models.CASCADE, null=True)
    receiver = models.ForeignKey(CustomUser, related_name='whoRecvRequest', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.sender.username)

    class Meta:
        ordering = ('sender',)  

Transcendence/Pong/models.py
from django.db import models

# Create your models here.

Transcendence/Display/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from Chat.models import CustomUser

class CreateUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'is_42_student']


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['profile_picture']

Transcendence/Api/Pong/views.py
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, UpdateAPIView
from rest_framework.response import Response
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from Api.Pong.serializers import PongInvitePostSerializer, PongInviteGetSerializer, PongInvitePutSerializer, PongInviteDeleteSerializer
from Api.Pong.models import PongInvite
import json
from rest_framework.permissions import IsAuthenticated

invite_json = {
    "invite_id": "{{invitee_name}}",
    "invitee": "tacikgoz",
    "invited": "admin",
    "is_active": 0
}


class PongInviteCreateAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request, *args, **kwargs):
        serializer = PongInvitePostSerializer(data=request.data)
        if serializer.is_valid():
            data = serializer.validated_data
            channel_layer = get_channel_layer()
            message = {
                'type': 'pongInvite',
                'action': 'pong_request',
                'username': data['invitee'],
                'friend': data['invited'],
                'update': 'pong_invite'
            }
            async_to_sync(channel_layer.group_send)(
                'chat',
                message
            )
            serializer.save()
            return Response({'status': True, 'data': data})
        return Response({'status': False, 'data': serializer.errors})

    def get(self, request, *args, **kwargs):
        invites = PongInvite.objects.all()
        serializer = PongInviteGetSerializer(invites, many=True)
        return Response({'status': True, 'data': serializer.data})

class PongInviteGetAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, inv_id, *args, **kwargs):
        try:
            instance = PongInvite.objects.get(invite_id=inv_id)
        except PongInvite.DoesNotExist:
            return Response({'status':'404 instance not found.'})
        
        serializer = PongInviteGetSerializer(instance, data=request.data)
        if serializer.is_valid():
            return Response({"status": True, "data": serializer.data})
        else:
            return Response({"status": False, "data": serializer.errors})


class PongInviteUpdateAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def put(self, request, inv_id, *args, **kwargs):
        try:
            instance = PongInvite.objects.get(invite_id=inv_id)
        except PongInvite.DoesNotExist:
            return Response({'status':'404 instance not found.'})
        
        serializer = PongInvitePutSerializer(instance, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({'status': True, 'data': serializer.data})
        else:
            return Response({'status': False, 'data': serializer.errors})

    def get(self, request, *args, **kwargs):
        invites = PongInvite.objects.all()
        serializer = PongInviteGetSerializer(invites, many=True)
        return Response({'status': True, 'data': serializer.data})


class PongInviteDeleteAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def delete(self, request, inv_id, *args, **kwargs):
        try:
            instance = PongInvite.objects.get(invite_id=inv_id)
        except PongInvite.DoesNotExist:
            return Response({'status': False, 'data': '404 instance not found.'})
        instance.delete()
        return Response({'status': True, 'data': 'Delete succesfully.'})
    
    def get(self, request, inv_id, *args, **kwargs):
        try:
            instance = PongInvite.objects.get(invite_id=inv_id)
        except PongInvite.DoesNotExist:
            return Response({'status':False, 'data': '404 instance not found.'})
        serializer = PongInviteGetSerializer(instance, data=request.data)
        if serializer.is_valid():
            return Response({'status': True, 'data': serializer.data})
        return Response({'status': False})

Transcendence/Api/Profile/views.py
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.response import Response

from django.shortcuts import get_object_or_404

from Chat.models import CustomUser
from .serializer import ProfileSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import permission_classes
from Display.forms import ProfilePictureForm
import os


@api_view(['GET', 'POST', 'PUT'])
@permission_classes([IsAuthenticated])
def product_alt_view(request, username=None, *args, **kwargs):
    method = request.method

    if method == "GET":
        if username is not None: # detail view
            obj = get_object_or_404(CustomUser, username=username)
            data = ProfileSerializer(obj, many=False).data
            return Response(data)
        # list view
        queryset = CustomUser.objects.all()
        data = ProfileSerializer(queryset, many=True).data
        return Response(data)

    if method == "PUT":
        if username is not None:
            try:
                user = CustomUser.objects.get(username=username)
            except CustomUser.DoesNotExist:
                return Response({'error': 'User not found'}, status=404)
            if request.FILES.get('profile_picture'):
                old_profile_picture = user.profile_picture
                form = ProfilePictureForm(instance=user, data=request.data, files=request.FILES)
                if form.is_valid():
                    form.save()
                    if old_profile_picture and old_profile_picture.path != "/usr/src/app/media/default/default.jpg":
                        os.remove(old_profile_picture.path)
                return Response(ProfileSerializer(user).data, status=200)

            serializer = ProfileSerializer(user, data=request.data, partial=True)
            if serializer.is_valid(raise_exception=True):
                serializer.save()
                return Response(serializer.data, status=200)
            else:
                return Response(serializer.errors, status=401)
        else:
            return Response({'error': 'Username is required for PUT requests'}, status=402)
        
    if method == "POST":
        serializer = ProfileSerializer(data=request.data)

        if serializer.is_valid(raise_exception=True):
            title = serializer.validated_data.get("title")
            content = serializer.validated_data.get("content") or None
            if content is None:
                content = title
            serializer.save(content=content)
            return Response(serializer.data)
        return Response({"invalid": "not good data"}, status=400)

Transcendence/Pong/views.py
from django.shortcuts import render
from django.http import  HttpResponse
from django.template import loader
from Chat.models import CustomUser

def pongPage(request, filename):
	user = CustomUser.objects.get(username=request.user)
	context = {
		'user': user,
	}
	temp = loader.get_template('Display/pong.html')
	return HttpResponse(temp.render(context))

Transcendence/templates/Display/about.html
<div class="container" id="about-container">
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card usercard">
        <img src="../../static/Display/img/tahil.jpg" class="card-img-top about_card" alt="Team Member">
        <div class="card-body">
          <h5 class="card-title">Talha AÇIKGÖZ</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card usercard">
        <img src="../../static/Display/img/sarp.jpg" class="card-img-top about_card" alt="Team Member">
        <div class="card-body">
          <h5 class="card-title">Yiğit Sarp ERKİRALP</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card usercard">
        <img src="../../static/Display/img/alp.jpg" class="card-img-top about_card" alt="Team Member">
        <div class="card-body">
          <h5 class="card-title">Alp Arda YALMAN</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card usercard">
        <img src="../../static/Display/img/EYUP.jpg" class="card-img-top about_card" alt="Team Member">
        <div class="card-body">
          <h5 class="card-title">Eyüp Kemal KARAOĞLU</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card usercard">
        <img src="../../static/Display/img/emircan.jpg" class="card-img-top about_card" alt="Team Member">
        <div class="card-body">
          <h5 class="card-title">Emircan KAYMAZ</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    <!-- Diğer ekip üyeleri için aynı kart yapısını kullanabilirsiniz -->
  </div>
</div>

Transcendence/templates/Display/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transcendence</title>

  <script type="importmap">
      {
        "imports": {
        "three": "https://unpkg.com/three@v0.149.0/build/three.module.js",
        "three/addons/": "https://unpkg.com/three@v0.149.0/examples/jsm/"
        }
      }
      </script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link href="{% static 'Display/css/main.css' %}" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

  <link href="{% static 'Display/css/nav.css' %}" rel="stylesheet">
  <link href="{% static 'Display/css/settings.css' %}" rel="stylesheet">
  <link href="{% static 'Display/css/login.css' %}" rel="stylesheet">
  <link href="{% static 'Display/css/profile.css' %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <style>
  </style>
  <link rel="shortcut icon" href="media/images.png" type="image/x-icon">
</head>


<body class="backgroundimage">
  <div class="userName" id="{{user.username}}"></div>
  <div id="navigation">
    {% include 'Display/nav.html' %}

    <div class="toast" role="alert" id="EpicToast-invite" aria-live="polite" aria-atomic="true" style="position: fixed; bottom: 10px; left: 10px; z-index: 10">
      <div class="toast-body">
        <strong class="me-auto" id="toast-invite-title">Tahil Has invited you to play pong</strong>
        <div class="mt-2 pt-2 border-top">
          <button type="button" class="btn btn-primary btn-sm" id="accept-pong-invite" onclick="inviteAccepting()" data-bs-dismiss="toast">Take action</button>
          <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="toast">Close</button>
        </div>
      </div>
    </div>
    

    <div class="toast" role="alert" id="EpicToast-chat" aria-live="assertive" aria-atomic="true"
      style="position: absolute; margin-left: 88%;">
      <div class="toast-header">
        <strong class="me-auto" id="toast-title"></strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body" id="toast-message">
        Test.
      </div>
    </div>

  </div>



  <div id="app">

  </div>

  <script src="{% static 'Display/js/navi.js' %}"></script>


</body>

</html>

Transcendence/templates/Display/login.html
<section class="vh-100">
	<div class="container-fluid h-custom">
		<div class="row d-flex justify-content-center align-items-center h-100">
			<div class="col-md-9 col-lg-6 col-xl-5">
				<img id="login42logo" src="../../static/Display/img/42_Logo.png" class="img-fluid" alt="Sample image">
			</div>
			<div class="col-md-8 col-lg-6 col-xl-4">
				<form>
					<div class="d-flex">
						<p class="lead fw-normal mb-0 me-3">Sign in with</p>
						<button type="button" class="btn btn-primary" id="FtButton">
							<img src="../../static/Display/img/42_Logo.png" style="width: 40px; height: 40px;"></img>
						</button>
					</div>
					<div class="divider my-4">
					</div>

					<!-- Email input -->
					<div class="mb-4">
						<label class="form-label">Name</label>
						<input type="text" class="form-control form-control-lg usernameLogin"
							placeholder="Username.." />
					</div>

					<!-- Password input -->
					<div class="mb-4">
						<label class="form-label">Password</label>
						<input type="password" class="form-control form-control-lg passwordLogin"
							placeholder="Enter password" />
					</div>

					<div class="text-center text-lg-start mt-4 pt-2">
						<button type="button" class="btn btn-primary btn-lg" id="login_btn">Login</button>
						<p class="small fw-bold ">Don't have an account?
							<a id="registerButtonInLoginPage" href="/register" class="link-danger">Register</a>
						</p>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>

Transcendence/templates/Display/nav.html
<nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" id="navbarhomet" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navbarProText" href="/profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navbarChatText" href="/chat">Chat</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navbarGameText" href="/pong">Game</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navbarSetText" href="/settings">Settings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navbarAboutText" href="/about">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" id="navbarLogoutText" href="{% url 'logout' %}"> Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Transcendence/templates/Display/register.html
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="../../static/Display/img/42_Logo.png" style="width: 500px;" class="img-fluid"
                    alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4">
                <form class="validate-form" method="POST" action="">
                    <!-- Username input -->
                    <div class="form-outline mb-4">
                        <input type="text" class="form-control form-control-lg" id="username"
                            placeholder="Username..." />
                    </div>
                    <!-- Firstname input -->
                    <div class="form-outline mb-4">
                        <input type="text" class="form-control form-control-lg" id="firstname" name="firstname"
                            placeholder="Firstname..." />
                    </div>
                    <!-- Lastname input -->
                    <div class="form-outline mb-4">
                        <input type="text" class="form-control form-control-lg" id="lastname" name="lastname"
                            placeholder="Lastname..." />
                    </div>
                    <!-- email input -->
                    <div class="form-outline mb-4">

                        <input type="email" class="form-control form-control-lg" id="email" name="email"
                            placeholder="Email..." />

                    </div>

                    <!-- Password input -->
                    <div class="form-outline mb-3">
                        <input type="password" id="password1" class="form-control form-control-lg passwordLogin"
                            name="password1" placeholder="Password..." />
                    </div>
                    <div class="form-outline mb-3">
                        <input type="password" id="password2" class="form-control form-control-lg" name="password2"
                            placeholder="Password..." />
                    </div>
                        <input class="btn btn-primary registerBtn" type="submit" value="Register">
                        <!-- Button text changed to Register -->
                    <!-- Button text changed to Register -->
                    <p class="small fw-bold mt-2">Don't have an account?
                        Already have an account?<a id="signInButtonInRegisterPage" class="p-2" href="/login">Sign
                            In</a> <!-- Link text changed to Sign In -->
                    </p>
            </div>
            </form>
        </div>
    </div>
</section>

Transcendence/templates/Display/settings.html
<div class="container">
    <div class="card" id="mycard">
        <div class="row no-gutters row-bordered row-border-light">
            <div class="col-md-7" id="settingcard">
                <div class="card-body media align-items-center">
                    <img class="setAvatar" src="{{ profile_photo }}" alt="" id="foto">
                    <form id="profile-picture-form" enctype="multipart/form-data">
                        <input type="file" name="profile_picture" id="id_profile_picture" 
                            class="custom-file-input btn btn-primary mt-1">
                        <button class="btn btn-primary mt-1" type="submit" id="settings-upload">Upload</button>
                    </form>
                    <div id="preview"></div>
                    <div class="form-group settingsFormInput">
                        <label for="FormUser" id="usernameText" class="form-label">username</label>
                        <input id="FormUser" type="text" class="form-control mb-1 username" value="{{user.username}}"
                            readonly>
                    </div>
                    <div class="form-group">
                        <label for="firstName" id="firstnameText" class="form-label">firstname</label>
                        <input type="text" class="form-control first_name" id="firstName" value="">
                    </div>
                    <div class="form-group">
                        <label for="lastName" id="lastnameText" class="form-label">lastname</label>
                        <input type="text" class="form-control last_name" id="lastName" value="">
                    </div>
                    <div class="form-group">
                        <label for="userEmail" id="emailText" class="form-label">email</label>
                        <input type="text" class="form-control useremail" id="userEmail" value="">
                    </div>
                    <div class="form-group">
                        <label class="form-label" id="bioText">bio</label>
                        <input type="text" class="form-control bio" value="">
                    </div>
                    <div class="text-right mt-3">
                        <button type="button" class="btn btn-primary" id="EN" onclick="changeLanguage('EN')">EN</button>&nbsp;
                        <button type="button" class="btn btn-primary" id="TR" onclick="changeLanguage('TR')">TR</button>&nbsp;
                        <button type="button" class="btn btn-primary" id="FR" onclick="changeLanguage('FR')">FR</button>&nbsp;
                    </div>
                    <div class="text-right mt-3">
                        <button type="submit" class="btn btn-primary" id="SettingsButtonSave">Save
                            changes</button>&nbsp;
                        <button type="button" class="btn btn-primary" id="TwofaButtonActivate">Enable 2FA</button>&nbsp;
                        <button type="button" class="btn btn-danger" id="DeleteUser">Delete account</button>&nbsp;
                    </div>
                    <div id="qrcode-container"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Transcendence/templates/Display/username.html
{{ username }}